name = "SurrealDB"
uuid = "0dc7cda7-6a2c-4f49-b8ae-2ed91ee7b183"
authors = ["Mattia Careddu"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
